"""
Validation utilities for KodiDevKit.
"""

import os
import re
import logging
from functools import lru_cache

logger = logging.getLogger("KodiDevKit.utils.validation")
if not logger.handlers:
    logger.addHandler(logging.NullHandler())
logger.propagate = True


def is_runtime_generated_file(file_path):
    """
    Check if file is generated by script.skinvariables runtime addon.

    Args:
        file_path: Absolute path to the file

    Returns:
        bool: True if file is generated at runtime by script.skinvariables
    """
    if not file_path:
        return False

    filename = os.path.basename(file_path).lower()

    # Only script-skinvariables-*.xml files (not skinshortcuts per user preference)
    # Examples: script-skinvariables-labels-includes.xml, script-skinvariables-images-includes.xml
    return filename.startswith('script-skinvariables-')


def normalize_control_id(control_id):
    """
    Normalize control ID by stripping leading zeros (matching Kodi's integer parsing).

    Kodi parses control IDs as integers via XMLUtils::GetInt, so "05" becomes 5.
    This ensures "05" and "5" are treated as the same control ID.

    Args:
        control_id: String control ID (e.g., "05", "5", "123")

    Returns:
        Normalized string with leading zeros removed (e.g., "5", "5", "123")
        Returns original string if not numeric or if it's just "0"
    """
    if not control_id or not isinstance(control_id, str):
        return control_id

    if not control_id.isdigit():
        return control_id

    normalized = control_id.lstrip('0') or '0'
    return normalized


def create_issue(message, file="", line=0, **kwargs):
    """
    Create a standardized validation issue dictionary.

    Args:
        message: Error message describing the issue
        file: File path where issue was found
        line: Line number where issue was found
        **kwargs: Additional fields to include (e.g., type, name, identifier)

    Returns:
        Dict with standardized issue format
    """
    issue = {
        "message": message,
        "file": file,
        "line": line,
    }
    issue.update(kwargs)
    return issue


_PARAM_PATTERN = re.compile(r'\$PARAM\[([^\]]+)\]')


def resolve_param_in_name(name, param_context=None, cache=None):
    """
    Resolve $PARAM[...] references in a name using parameter values.

    Matches Kodi's parameter resolution (GUIIncludes.cpp). Undefined params
    become empty strings.

    Args:
        name: Name that may contain $PARAM references
        param_context: Dict of parameter values
        cache: Optional dict for caching results

    Returns:
        Resolved name with $PARAM replaced by values
    """
    if not name or "$PARAM[" not in name:
        return name

    cache_key = None
    if cache is not None:
        cache_key = (name, frozenset(param_context.items()) if param_context else frozenset())
        if cache_key in cache:
            return cache[cache_key]

    def replace_param(match):
        param_name = match.group(1)
        if param_context and param_name in param_context:
            return param_context[param_name]
        return ''

    resolved = _PARAM_PATTERN.sub(replace_param, name)

    if cache is not None and cache_key is not None:
        cache[cache_key] = resolved

    return resolved


def get_all_parameter_contexts(addon, folder):
    """
    Get all parameter contexts from include usages in a folder.

    When a name contains $PARAM, we check all contexts where the containing
    include is used to see if it resolves to something defined.

    Args:
        addon: Addon/Skin instance with include_usages and index_builder
        folder: XML folder (e.g., '1080i')

    Returns:
        List of parameter context dicts
    """
    if not addon._include_usages_built:
        addon.index_builder.build_include_usages()

    all_contexts = []
    for _inc_name, usages in addon.include_usages.get(folder, {}).items():
        for usage in usages:
            all_contexts.append(usage['params'])

    all_contexts.append({})
    return all_contexts


def should_report_progress(count, total):
    """Throttle progress: always first 10, then every 10 (large) or every 3."""
    if count <= 10:
        return True
    if total > 100:
        return count % 10 == 0
    return count % 3 == 0


def deduplicate_issues(issues):
    """Deduplicate validation issues by (file, line, message) key."""
    seen = set()
    result = []
    for issue in issues:
        key = (issue['file'], issue['line'], issue['message'])
        if key not in seen:
            seen.add(key)
            result.append(issue)
    return result


def find_unused_items(definitions, references, item_type, skip_filter=None):
    """
    Find items that are defined but never used.

    Args:
        definitions: List of definition nodes from addon.includes[folder]
        references: List of reference dicts with "name" key
        item_type: Type of item (e.g., "variable", "include", "font")
        skip_filter: Optional function to skip certain definitions (e.g., runtime-generated patterns)

    Returns:
        List of issue dicts for unused items
    """
    ref_names = {ref["name"] for ref in references}
    unused = []

    for node in definitions:
        if node.get("type") == item_type and node.get("name") not in ref_names:
            if skip_filter and skip_filter(node):
                continue

            unused.append(
                create_issue(
                    f"Unused {item_type}: {node['name']}",
                    file=node.get("file") or "",
                    line=node.get("line") or 0,
                    type=item_type,
                    name=node["name"]
                )
            )

    return unused


def find_undefined_items(references, definitions, item_type, skip_filter=None):
    """
    Find items that are used but not defined.

    Args:
        references: List of reference dicts with "name" key
        definitions: List of definition nodes from addon.includes[folder]
        item_type: Type of item (e.g., "variable", "include", "font")
        skip_filter: Optional function to skip certain references (e.g., lambda ref: ref["name"].startswith("$"))

    Returns:
        List of issue dicts for undefined items
    """
    defined_names = {
        node.get("name")
        for node in definitions
        if node.get("type") == item_type and node.get("name")
    }

    undefined = []
    for ref in references:
        if skip_filter and skip_filter(ref):
            continue

        if ref["name"] not in defined_names:
            ref["message"] = f"{item_type.capitalize()} not defined: {ref['name']}"
            undefined.append(ref)

    return undefined


def resolve_include_content(inc, resolve_callback=None):
    """
    Return include XML text with $PARAM placeholders resolved.

    Args:
        inc: Include definition (dict or object with content/params attributes)
        resolve_callback: Optional callback function to use instead of default resolution

    Returns:
        Resolved XML content string
    """
    # Import here to avoid circular dependency
    from .expressions import resolve_params_in_text

    if resolve_callback:
        return resolve_callback(inc)

    content = inc.get("content") or "" if hasattr(inc, "get") else getattr(inc, "content", "") or ""
    if not content:
        return ""

    params = getattr(inc, "params", None) or {}
    try:
        resolved_text, _ = resolve_params_in_text(content, params)
        return resolved_text
    except Exception:
        logger.debug("Failed to resolve params for include %s", getattr(inc, "name", "<unknown>"))
        return content


@lru_cache(maxsize=128)
def _get_font_name_pattern(font_name):
    """
    Return cached regex pattern for matching font name in XML.

    Args:
        font_name: Name of font to search for

    Returns:
        Compiled regex pattern
    """
    return re.compile(r"<name>\s*%s\s*</name>" % re.escape(font_name), re.I)


def find_font_line_in_include(inc, font_name):
    """
    Return 1-based line number of the <font> block defining font_name in include.

    Searches the include file for a <name>font_name</name> tag, then walks backward
    to find the opening <font> tag for that definition.

    Args:
        inc: Include definition dict with "file" and "line" keys
        font_name: Name of font to search for

    Returns:
        1-based line number of <font> opening tag, or include line if not found
    """
    path = (inc.get("file") or "").strip()
    if not path or not os.path.isfile(path):
        return int(inc.get("line") or 1)

    try:
        with open(path, encoding="utf8", errors="ignore") as f:
            lines = list(f)

        start = max(int(inc.get("line") or 1) - 1, 0)
        pat = _get_font_name_pattern(font_name)  # Use cached pattern

        for i in range(start, len(lines)):
            if pat.search(lines[i]):
                j = i
                while j >= 0 and "<font" not in lines[j].lower():
                    j -= 1
                return (j if j >= 0 else i) + 1
    except Exception:
        pass

    return int(inc.get("line") or 1)


def _is_runtime_placeholder(text):
    """Check if text contains a runtime placeholder that can't be resolved statically."""
    upper = text.upper()
    return "$SKINSHORTCUTS" in upper or "$PROPERTY[" in upper


def find_skinshortcuts_template(addon_path):
    """
    Find the SkinShortcuts template file (v2 or v3).

    v3 uses templates.xml (plural), v2 uses template.xml (singular).

    Returns:
        Path to template file if found, None otherwise.
    """
    shortcuts_dir = os.path.join(addon_path, "shortcuts")
    # v3 first (preferred)
    for filename in ("templates.xml", "template.xml"):
        path = os.path.join(shortcuts_dir, filename)
        if os.path.isfile(path):
            return path
    return None


def find_includes_in_skinshortcuts_template(template_path, known_include_names):
    """
    Find skin includes referenced in a SkinShortcuts template file (v2 or v3).

    Scans text content, ``<include>`` tags, and ``content``/``include``
    attributes on ``<include>`` and ``<skinshortcuts>`` elements.

    References containing ``$SKINSHORTCUTS[...]`` or ``$PROPERTY[...]``
    are skipped (runtime placeholders).

    Args:
        template_path: Path to shortcuts/template.xml or templates.xml
        known_include_names: Set of include names defined in the skin

    Returns:
        Set of include names found in the template
    """
    from .xml import get_root_from_file

    if not os.path.isfile(template_path):
        return set()

    root = get_root_from_file(template_path)
    if root is None:
        return set()

    referenced = set()

    try:
        # Text content (v2 property values + v3 <include>Name</include>)
        for text in root.xpath(".//text()"):
            text_stripped = text.strip()
            if not text_stripped or _is_runtime_placeholder(text_stripped):
                continue
            for include_name in known_include_names:
                if include_name in text_stripped:
                    referenced.add(include_name)

        # v3: <include content="Name"> and <skinshortcuts include="Name">
        for attr in ("content", "include"):
            for elem in root.xpath(f".//*[@{attr}]"):
                value = elem.get(attr, "")
                if not value or _is_runtime_placeholder(value):
                    continue
                if value in known_include_names:
                    referenced.add(value)

    except Exception:
        logger.exception("Error parsing SkinShortcuts template at %s", template_path)

    return referenced


def find_variables_in_skinshortcuts_template(template_path, known_variable_names):
    """
    Find skin variables referenced in a SkinShortcuts template file (v2 or v3).

    Scans both text content and attribute values for ``$VAR[Name]`` /
    ``$ESCVAR[Name]`` patterns.

    References containing ``$SKINSHORTCUTS[...]`` or ``$PROPERTY[...]``
    are skipped (runtime placeholders).

    Args:
        template_path: Path to shortcuts/template.xml or templates.xml
        known_variable_names: Set of variable names defined in the skin

    Returns:
        Set of variable names found in the template
    """
    from .xml import get_root_from_file

    if not os.path.isfile(template_path):
        return set()

    root = get_root_from_file(template_path)
    if root is None:
        return set()

    referenced = set()
    var_pattern = re.compile(r"\$(?:ESC)?VAR\[(.*?)\]", re.IGNORECASE)

    def _scan(text):
        for match in var_pattern.finditer(text):
            var_name = match.group(1).split(",")[0]
            if _is_runtime_placeholder(var_name):
                continue
            if var_name in known_variable_names:
                referenced.add(var_name)

    try:
        for text in root.xpath(".//text()"):
            text_stripped = text.strip()
            if text_stripped:
                _scan(text_stripped)

        # Attribute values (v3 templates use $VAR[] in attributes like colordiffuse)
        for elem in root.iter():
            for value in elem.attrib.values():
                if "$VAR[" in value.upper() or "$ESCVAR[" in value.upper():
                    _scan(value)

    except Exception:
        logger.exception("Error parsing SkinShortcuts template for variables at %s", template_path)

    return referenced


def find_variable_definitions_in_skinshortcuts_template(template_path):
    """
    Find variable names defined inside a SkinShortcuts template file.

    Templates can contain ``<variable name="X">`` blocks that SkinShortcuts
    generates into the runtime includes file. The skin references these
    with ``$VAR[X]`` but no static definition exists in the skin's own
    includes -- so they must be treated as defined to avoid false positives.

    Names containing runtime placeholders (``$SKINSHORTCUTS``, ``$PROPERTY``)
    are skipped since the actual name can't be determined statically.

    Args:
        template_path: Path to shortcuts/template.xml or templates.xml

    Returns:
        Set of variable names defined in the template
    """
    from .xml import get_root_from_file

    if not os.path.isfile(template_path):
        return set()

    root = get_root_from_file(template_path)
    if root is None:
        return set()

    defined = set()
    try:
        for var_elem in root.iter("variable"):
            name = var_elem.get("name", "").strip()
            if name and not _is_runtime_placeholder(name):
                defined.add(name)
    except Exception:
        logger.exception("Error scanning variable definitions in %s", template_path)

    return defined
