"""Type stubs for Sublime Text Plugin API."""

from typing import Any, Optional
import sublime

class EventListener:
    def on_load(self, view: sublime.View) -> None: ...
    def on_load_async(self, view: sublime.View) -> None: ...
    def on_close(self, view: sublime.View) -> None: ...
    def on_pre_close_window(self, window: sublime.Window) -> None: ...
    def on_activated(self, view: sublime.View) -> None: ...
    def on_activated_async(self, view: sublime.View) -> None: ...
    def on_deactivated(self, view: sublime.View) -> None: ...
    def on_deactivated_async(self, view: sublime.View) -> None: ...
    def on_modified(self, view: sublime.View) -> None: ...
    def on_modified_async(self, view: sublime.View) -> None: ...
    def on_selection_modified(self, view: sublime.View) -> None: ...
    def on_selection_modified_async(self, view: sublime.View) -> None: ...
    def on_post_save(self, view: sublime.View) -> None: ...
    def on_post_save_async(self, view: sublime.View) -> None: ...
    def on_hover(self, view: sublime.View, point: int, hover_zone: int) -> None: ...

class ApplicationCommand:
    def run(self, **kwargs: Any) -> None: ...
    def is_enabled(self, **kwargs: Any) -> bool: ...
    def is_visible(self, **kwargs: Any) -> bool: ...

class TextCommand:
    def __init__(self, view: sublime.View) -> None: ...
    view: sublime.View
    def run(self, edit: Any, **kwargs: Any) -> None: ...

class WindowCommand:
    def __init__(self, window: sublime.Window) -> None: ...
    window: sublime.Window
    def run(self, **kwargs: Any) -> None: ...
